openapi: 3.0.3
info:
  title: School Management API
  version: 1.0.0
servers:
  - url: https://yourusername.github.io/school-api
    description: GitHub Pages server

paths:
  /classes:
    get:
      summary: List all classes
      responses:
        '200':
          description: A list of classes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Class'
    post:
      summary: Create a new class
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Class'
      responses:
        '201':
          description: Class created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'

  /classes/{id}:
    get:
      summary: Get class by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Class found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Class'
        '404':
          description: Not found
    put:
      summary: Update class
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Class'
      responses:
        '200':
          description: Class updated
    delete:
      summary: Delete class
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Class deleted

# Repeat similar paths for Students, Teachers, Subjects, TeacherAssignments, LessonSchedule,
# LessonLogs, StudentLessons, AttendanceStatuses

components:
  schemas:
    Class:
      type: object
      properties:
        id:
          type: integer
        grade:
          type: integer
        letter:
          type: string
          maxLength: 1
      required:
        - grade
        - letter

    Student:
      type: object
      properties:
        id:
          type: integer
        class_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        patronymic:
          type: string
      required:
        - class_id
        - first_name
        - last_name

    Teacher:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        patronymic:
          type: string
      required:
        - first_name
        - last_name

    Subject:
      type: object
      properties:
        id:
          type: integer
        subject_name:
          type: string
      required:
        - subject_name

    AttendanceStatus:
      type: object
      properties:
        code:
          type: string
          maxLength: 1
        description:
          type: string
      required:
        - code
        - description
